# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LyJvWZ0wI2qVhLNIXOZyhHYw-b4AtujF
"""

# app.py

import streamlit as st
import pandas as pd
from pandas import DataFrame
import joblib

# Load the vectorizer and model (adjust filenames to yours)
cv = joblib.load("vectorizer.joblib")
lr = joblib.load("model.joblib")

st.title("Text Classification Demo")

# User input
sentence = st.text_input("Enter a sentence:", "")

if st.button("Predict"):
    if sentence:
        # Convert the sentence to the vectorized form
        Snew = cv.transform([sentence])
        # Predict
        result = lr.predict(Snew)
        # Display result
        st.write(f"Prediction: **{result[0]}**")
    else:
        st.warning("Please enter some text.")